"""users table

Revision ID: 8fe09e468091
Revises: 
Create Date: 2022-05-12 16:31:08.460891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fe09e468091'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bike_news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('news_title', sa.String(length=80), nullable=True),
    sa.Column('news_text', sa.String(), nullable=True),
    sa.Column('news_photo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bike_news')
    # ### end Alembic commands ###
